const jokes = [
  "Why don't scientists trust atoms? Because they make up everything!",
  "Why did the scarecrow win an award? Because he was outstanding in his field!",
  "Why don't skeletons fight each other? They don't have the guts.",
  "I'm reading a book on anti-gravity. It's impossible to put down!",
  "Did you hear about the mathematician who’s afraid of negative numbers? He’ll stop at nothing to avoid them.",
  "Why don’t some couples go to the gym? Because some relationships don’t work out.",
  "I would tell you a joke about an elevator, but it's an uplifting experience.",
  "What do you get when you cross a snowman and a vampire? Frostbite.",
  "Why did the bicycle fall over? Because it was two-tired!",
  "I’m on a whiskey diet. I’ve lost three days already.",
  "Parallel lines have so much in common. It’s a shame they’ll never meet.",
  "What did one wall say to the other? I’ll meet you at the corner.",
  "Why can’t you hear a pterodactyl go to the bathroom? Because the “P” is silent.",
  "How does a penguin build its house? Igloos it together.",
  "I told my wife she was drawing her eyebrows too high. She looked surprised.",
  "Why don’t programmers like nature? It has too many bugs.",
  "I told my computer I needed a break, and now it won't stop sending me Kit Kats.",
  "I would tell you a chemistry joke, but I know I wouldn’t get a reaction.",
  "Why did the golfer bring two pairs of pants? In case he got a hole in one.",
  "Why don’t oysters share their pearls? Because they’re shellfish.",
  "Why are elevator jokes so good? They work on so many levels.",
  "What did the janitor say when he jumped out of the closet? Supplies!",
  "Why don’t you ever see elephants hiding in trees? Because they’re so good at it.",
  "I used to play piano by ear, but now I use my hands.",
  "How do you organize a space party? You planet.",
  "Why don’t skeletons ever go trick or treating? Because they have no body to go with.",
  "I made a pencil with two erasers. It was pointless.",
  "What did the grape do when he got stepped on? Nothing but let out a little wine.",
  "What kind of shoes do ninjas wear? Sneakers.",
  "Why don’t cows have any money? Because the farmers milk them dry.",
  "What did the buffalo say when his son left for college? Bison.",
  "I got hit in the head with a can of soda. Luckily, it was a soft drink.",
  "Why don’t you play cards in the jungle? Too many cheetahs.",
  "What kind of car does a sheep drive? A lamborghini.",
  "Why did the coffee file a police report? It got mugged.",
  "What’s brown and sticky? A stick.",
  "What do you call fake spaghetti? An impasta.",
  "How does a train eat? It goes chew chew.",
  "Why was the math book sad? It had too many problems.",
  "What do you call a dinosaur with an extensive vocabulary? A thesaurus.",
  "Why can’t your nose be 12 inches long? Because then it’d be a foot.",
  "Why did the tomato turn red? Because it saw the salad dressing!",
  "How do you make holy water? You boil the hell out of it.",
  "Why don’t some fish play piano? Because you can’t tuna fish.",
  "Why did the chicken go to the seance? To talk to the other side.",
  "I once told a chemistry joke. There was no reaction.",
  "Why did the math teacher go to therapy? Because he had too many problems.",
  "What do you call cheese that isn’t yours? Nacho cheese.",
  "Why was the big cat disqualified from the race? Because it was a cheetah.",
  "What do you get when you cross a cow and a duck? Milk and quackers.",
  "I used to be a baker, but I couldn’t make enough dough.",
  "Why don’t vampires attack Taylor Swift? She has bad blood.",
  "Why are frogs so happy? Because they eat whatever bugs them.",
  "What do you call a bear with no teeth? A gummy bear.",
  "Why do seagulls fly over the ocean? Because if they flew over the bay, they’d be bagels.",
  "What’s the difference between a well-dressed man on a unicycle and a poorly dressed man on a bike? Attire.",
  "What do you call a can opener that doesn’t work? A can’t opener.",
  "Why did the scarecrow become a successful neurosurgeon? Because he was outstanding in his field.",
  "I stayed up all night wondering where the sun went. Then it dawned on me.",
  "What do you call an alligator in a vest? An investigator.",
  "I told a joke about amnesia, but I forgot the punchline.",
  "Why did the mushroom go to the party alone? Because he’s a fungi.",
  "I went to buy some camouflage pants, but I couldn’t find any.",
  "I tried to sue the airline for losing my luggage. I lost my case.",
  "I’m friends with all the people at the gym. We have a strong relationship.",
  "Why did the man get hit by a bike every day? He was stuck in a vicious cycle.",
  "What did the ocean say to the beach? Nothing, it just waved.",
  "What does a cloud wear under his raincoat? Thunderwear.",
  "Why don’t pirates shower before they walk the plank? Because they’ll just wash up on shore later.",
  "How do you make a tissue dance? Put a little boogie in it.",
  "Why did the math book go to therapy? It had too many problems.",
  "What did the left eye say to the right eye? Between you and me, something smells.",
  "I gave all my dead batteries away today. Free of charge.",
  "Why did the computer catch a cold? Because it left its Windows open.",
  "Why don’t we ever tell secrets on a farm? Because the potatoes have eyes and the corn has ears.",
  "Why did the golfer bring an extra pair of pants? In case he got a hole in one.",
  "Why don’t eggs tell jokes? Because they’d crack each other up.",
  "I told my wife she was drawing her eyebrows too high. She looked surprised.",
  "What kind of room doesn’t have doors? A mushroom.",
  "Why did the stadium get hot after the game? All the fans left.",
  "I have a joke about a broken pencil, but it’s pointless.",
  "Why can’t you give Elsa a balloon? Because she’ll let it go.",
  "Why do bees have sticky hair? Because they use honeycombs.",
  "What did the horse say after it tripped? Help! I’ve fallen and I can’t giddyup.",
  "What’s orange and sounds like a parrot? A carrot.",
  "How do you find Will Smith in the snow? Look for fresh prints.",
  "Why do cows wear bells? Because their horns don’t work.",
  "What does a nosy pepper do? It gets jalapeño business.",
  "Why don’t sharks like fast food? Because they can’t catch it.",
  "What kind of tree fits in your hand? A palm tree.",
  "Why was the calendar always nervous? Its days were numbered.",
  "I told a joke about construction, but I’m still working on it.",
  "What did the fish say when it hit the wall? Dam!",
  "Why did the grape stop in the middle of the road? Because it ran out of juice.",
  "Why don’t skeletons fight each other? They don’t have the guts.",
  "What did one wall say to the other? I’ll meet you at the corner.",
  "How does a penguin build its house? Igloos it together.",
  "Why don’t programmers like nature? It has too many bugs.",
  "Why did the coffee file a police report? It got mugged.",
  "What do you call fake spaghetti? An impasta.",
];

let random = Math.ceil(Math.random() * 100);
document.querySelector("#joke").innerHTML = jokes[random];